export const homeObj1 = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About",
  headLine: "HeadLine",
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc hendrerit sollicitudin ipsum nec porta. In placerat est non pretium porta. Mauris eu augue interdum, bibendum sapien vel, malesuada quam. Nullam quis velit malesuada purus congue maximus vitae a nulla. Duis luctus libero ac urna blandit fringilla. Ut ut suscipit augue. Morbi est ex, facilisis ut ultrices vel, scelerisque convallis erat. Mauris justo lectus, fermentum in nisl sed, interdum molestie risus.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../img/about.svg").default,
  alt: "about",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObj2 = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Discover",
  headLine: "HeadLine",
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc hendrerit sollicitudin ipsum nec porta. In placerat est non pretium porta. Mauris eu augue interdum, bibendum sapien vel, malesuada quam. Nullam quis velit malesuada purus congue maximus vitae a nulla. Duis luctus libero ac urna blandit fringilla. Ut ut suscipit augue. Morbi est ex, facilisis ut ultrices vel, scelerisque convallis erat. Mauris justo lectus, fermentum in nisl sed, interdum molestie risus.",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../img/discover.svg").default,
  alt: "discover",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObj3 = {
  id: "register",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Register",
  headLine: "HeadLine",
  desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc hendrerit sollicitudin ipsum nec porta. In placerat est non pretium porta. Mauris eu augue interdum, bibendum sapien vel, malesuada quam. Nullam quis velit malesuada purus congue maximus vitae a nulla. Duis luctus libero ac urna blandit fringilla. Ut ut suscipit augue. Morbi est ex, facilisis ut ultrices vel, scelerisque convallis erat. Mauris justo lectus, fermentum in nisl sed, interdum molestie risus.",
  buttonLabel: "Register",
  imgStart: true,
  img: require("../../img/signup.svg").default,
  alt: "register",
  dark: true,
  primary: false,
  darkText: true,
};
